export const ISSUE_LIST_REQUEST = "ISSUE_LIST_REQUEST";
export const ISSUE_LIST_SUCCESS = "ISSUE_LIST_SUCCESS";
export const ISSUE_LIST_FAIL = "ISSUE_LIST_FAIL";

export const ISSUE_DETAILS_REQUEST = "ISSUE_DETAILS_REQUEST";
export const ISSUE_DETAILS_SUCCESS = "ISSUE_DETAILS_SUCCESS";
export const ISSUE_DETAILS_FAIL = "ISSUE_DETAILS_FAIL";

export const ISSUE_UPDATE_REQUEST = "ISSUE_UPDATE_REQUEST";
export const ISSUE_UPDATE_SUCCESS = "ISSUE_UPDATE_SUCCESS";
export const ISSUE_UPDATE_RESET = "ISSUE_UPDATE_RESET";
export const ISSUE_UPDATE_FAIL = "ISSUE_UPDATE_FAIL";
