export const ISSUE_LIST_REQUEST = "ISSUE_LIST_REQUEST";
export const ISSUE_LIST_SUCCESS = "ISSUE_LIST_SUCCESS";
export const ISSUE_LIST_FAIL = "ISSUE_LIST_FAIL";

export const ISSUE_DETAILS_REQUEST = "ISSUE_DETAILS_REQUEST";
export const ISSUE_DETAILS_SUCCESS = "ISSUE_DETAILS_SUCCESS";
export const ISSUE_DETAILS_FAIL = "ISSUE_DETAILS_FAIL";

export const ISSUE_EDIT_REQUEST = "ISSUE_EDIT_REQUEST";
export const ISSUE_EDIT_SUCCESS = "ISSUE_EDIT_SUCCESS";
export const ISSUE_EDIT_FAIL = "ISSUE_EDIT_FAIL";

export const ISSUE_CREATE_REQUEST = "ISSUE_CREATE_REQUEST";
export const ISSUE_CREATE_SUCCESS = "ISSUE_CREATE_SUCCESS";
export const ISSUE_CREATE_RESET = "ISSUE_CREATE_RESET";
export const ISSUE_CREATE_FAIL = "ISSUE_CREATE_FAIL";

export const ISSUE_UPDATE_REQUEST = "ISSUE_UPDATE_REQUEST";
export const ISSUE_UPDATE_SUCCESS = "ISSUE_UPDATE_SUCCESS";
export const ISSUE_UPDATE_RESET = "ISSUE_UPDATE_RESET";
export const ISSUE_UPDATE_FAIL = "ISSUE_UPDATE_FAIL";
